apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongo-application-secrets
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
data:
  hostname: {{ .Values.mongo.hostname | b64enc }}
  port: {{ .Values.mongo.port | b64enc }}
  username: {{  .Values.mongo.username | b64enc  }}
  password: {{ .Values.mongo.rootPassword | b64enc }}