apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-application-secrets
  annotations:
    replicator.v1.mittwald.de/replication-allowed: "true"
    replicator.v1.mittwald.de/replication-allowed-namespaces: ".*"
data:
  postgresql-password: {{ .Values.mongo.rootPassword | b64enc }}
