expose:
  type: ingress
{{- if .Requirements.ingress.tls.enabled }}
  tls:
    enabled: true
{{- if .Requirements.ingress.tls.production }}
    secretName: "tls-{{ .Requirements.ingress.domain | replace "." "-" }}-p"
{{- else }}
    secretName: "tls-{{ .Requirements.ingress.domain | replace "." "-" }}-s"
{{- end }}
{{- end }}
  ingress:
    hosts:
      core: harbor.{{ .Requirements.ingress.domain }}
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

persistence:
  persistentVolumeClaim:
    registry:
      size: 100Gi
    database:
      size: 5Gi
    redis:
      size: 5Gi

externalURL: http://harbor.{{ .Requirements.ingress.domain }}
harborAdminPassword: local:simonjamesrowe/docker:password

chartmuseum:
  enabled: false

clair:
  enabled: false

notary:
  enabled: false
